<?php

namespace AST;

enum ASTNodeTypeEnum implements ASTNodeTypeEnumInterface {

	/*Properties
	**
	**
	*/

	// STRUCTURE

	case PROGRAM;
	case PROCEDURE;
	case FUNCTION ;
	case BLOCK ;

	// STATEMENTS

	case COMPOUND_STATEMENT;
	case ASSIGNMENT_STATEMENT;
	case PROCEDURES_STATEMENT;
	case IF_STATEMENT;
	case SELECT_STATEMENT;
	case SELECT_BRANCH_STATEMENT;
	case LOOP_STATEMENT;
	case SELECT_CONSTANTS_STATEMENT;
	case NOOP;
	case TEST_STATEMENT;
	case CALL_STATEMENT;
	case PARAMETERS_STATEMENT;
	case WHILE_STATEMENT;
	
	//ADD, SUBTRACT, OR, NEGATE

	case ADD_OPERATOR;
	case SUBTRACT_OPERATOR;
	case OR_OPERATOR;
	case NEGATE_OPERATOR;

	// MULTIPLY, INTEGER DIVIDE, FLOAT DIVIDE, MODULUS, AND

	case MULTIPLICATION_OPERATOR;
	case INTEGER_DIVISION_OPERATOR;
	case FLOAT_DIVISION_OPERATOR;
	case MODULUS_OPERATOR;
	case AND_OPERATOR;

	// EQUAL, NOT EQUAL, LESS THAN, LESS THAN EQUAL, GREATER THAN, GREATER THAN EQUAL

	case EQUAL;
	case NOT_EQUAL;
	case LESS_THAN;
	case LESS_THAN_EQUAL;
	case GREATER_THAN;
	case GREATER_THAN_EQUAL;

	// OPERANDS

	case VARIABLE;
	case SUBSCRIPTS;
	case FIELD;
	case BOOLEAN_CONSTANT;
	case INTEGER_CONSTANT;
	case REAL_CONSTANT;
	case STRING_CONSTANT;


	/*Methods
	**
	**
	*/

}
